### ISSUE TITLE
while building console-image I am getting the following error related to gcc

### ISSUE THREAD

**Issue by gmalmeida** [jumpnow/meta-wandboard#2]
I cannot attach the log as I do not have write permissions to this repository... nevertheless I send a part of it..

```bitbake
tree-vect-data-refs.c:(.text+0x748c): undefined reference to `size_binop_loc(unsigned int, tree_code, tree_node*, tree_node*)'
libbackend.a(tree-vect-data-refs.o): In function `vect_vfa_segment_size(data_reference*, tree_node*)':
tree-vect-data-refs.c:(.text+0x78cd): undefined reference to `fold_convert_loc(unsigned int, tree_node*, tree_node*)'
tree-vect-data-refs.c:(.text+0x78e2): undefined reference to `fold_convert_loc(unsigned int, tree_node*, tree_node*)'
tree-vect-data-refs.c:(.text+0x78f4): undefined reference to `size_binop_loc(unsigned int, tree_code, tree_node*, tree_node*)'
libbackend.a(tree-vect-data-refs.o): In function `vect_prune_runtime_alias_test_list(_loop_vec_info*)':
tree-vect-data-refs.c:(.text+0x7ae7): undefined reference to `operand_equal_p(tree_node const*, tree_node const*, unsigned int)'
tree-vect-data-refs.c:(.text+0x7b90): undefined reference to `size_int_kind(long, size_type_kind)'
tree-vect-data-refs.c:(.text+0x7bc5): undefined reference to `size_binop_loc(unsigned int, tree_code, tree_node*, tree_node*)'
tree-vect-data-refs.c:(.text+0x7be0): undefined reference to `size_binop_loc(unsigned int, tree_code, tree_node*, tree_node*)'
tree-vect-data-refs.c:(.text+0x7dc3): undefined reference to `operand_equal_p(tree_node const*, tree_node const*, unsigned int)'
tree-vect-data-refs.c:(.text+0x7fd2): undefined reference to `size_int_kind(long, size_type_kind)'
tree-vect-data-refs.c:(.text+0x7fea): undefined reference to `size_binop_loc(unsigned int, tree_code, tree_node*, tree_node*)'
libbackend.a(tree-vect-data-refs.o): In function `vect_get_new_vect_var(tree_node*, vect_var_kind, char const*)':
tree-vect-data-refs.c:(.text+0x4707): undefined reference to `create_tmp_reg(tree_node*, char const*)'
libbackend.a(tree-vect-data-refs.o): In function `vect_vfa_segment_size(data_reference*, tree_node*)':
tree-vect-data-refs.c:(.text+0x78b5): undefined reference to `size_binop_loc(unsigned int, tree_code, tree_node*, tree_node*)'
collect2: error: ld returned 1 exit status
make[1]: *** [lto1] Error 1
make[1]: Leaving directory `/media/data/playground/wandboard/meta-wandboard/build-wandboard/tmp/work/x86_64-poky-linux-gnueabi/gcc-cross-arm/4.9.2-r0/gcc-4.9.2/build.x86_64-linux.arm-poky-linux-gnueabi/gcc'
make: *** [all-gcc] Error 2
ERROR: oe_runmake failed
WARNING: /media/data/playground/wandboard/meta-wandboard/build-wandboard/tmp/work/x86_64-poky-linux-gnueabi/gcc-cross-arm/4.9.2-r0/temp/run.do_compile.26482:1 exit 1 from
  exit 1
ERROR: Function failed: do_compile (log file is located at /media/data/playground/wandboard/meta-wandboard/build-wandboard/tmp/work/x86_64-poky-linux-gnueabi/gcc-cross-arm/4.9.2-r0/temp/log.do_compile.26482)
```

**Comment by gmalmeida** [comment]
it sees there is a issue with gcc-4.9.2 recipe... I have used now 4.8.1 and it seems to be working...

**Comment by scottellis** [comment]
Hi Gabriel,

I am using gcc-4.9.2-r0 with multiple boards including the wandboard.
I rebuilt the wandboard stuff again this morning. I'm not seeing a problem.

Here's the compiler my build host is using

  scott@fractal:~/wandboard/build$ gcc --version
  gcc (Ubuntu 4.9.2-10ubuntu13) 4.9.2
  Copyright (C) 2014 Free Software Foundation, Inc.
  This is free software; see the source for copying conditions.  There is NO
  warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


And here's what the host is building with Yocto

  scott@fractal:~/wandboard/build$ bitbake -s | grep gcc
  gcc                                                 :4.9.2-r0
  gcc-cross-arm                                       :4.9.2-r0
  gcc-cross-canadian-arm                              :4.9.2-r0
  gcc-cross-initial-arm                               :4.9.2-r0
  gcc-crosssdk-initial-x86_64                         :4.9.2-r0
  gcc-crosssdk-x86_64                                 :4.9.2-r0
  gcc-runtime                                         :4.9.2-r0
  gcc-sanitizers                                      :4.9.2-r0
  gcc-source                                          :4.9.2-r0
  gccmakedep                                         1:1.0.3-r3
  libgcc                                              :4.9.2-r0
  libgcc-initial                                      :4.9.2-r0
  nativesdk-gcc-runtime                               :4.9.2-r0
  nativesdk-gcc-sanitizers                            :4.9.2-r0
  nativesdk-libgcc                                    :4.9.2-r0
  nativesdk-libgcc-initial                            :4.9.2-r0


And here's a wandboard quad boot log from this morning's build

  https://gist.github.com/scottellis/818e81623d4b493debcb


gcc-4.9.2 is the Yocto default for the [fido] branch. Since [fido] is the
stable branch, I think lots of people would be complaining if it was broken.

What build host are you using? I am using Ubuntu 15.04 64-bit servers.

BTW, I am going to push some updates to meta-wandboard shortly.

Kernel 4.2.4 is out so I upgraded the kernel recipe.

There were some yocto and meta-openembedded updates to the [fido] branch over
the last day or so. Mostly documentation stuff for yocto.

Regards,
Scott

**Comment by gmalmeida** [comment]
Thanks for your support Scott..

I am having Ubuntu 14.04 64-bit VM with gcc-4.8... 

I have just now upgraded it to gcc-4.9 and fetch the meta-openembedded repo again to include the gcc-4.9 recipes..

I keep you informed... build is in progress...

Thanks!

**Comment by gmalmeida** [comment]
still the same... :(

```code
collect2: error: ld returned 1 exit status
| make[1]: *** [cc1plus] Error 1
| make[1]: Leaving directory `/media/data/playground/wandboard/meta-wandboard/build-wandboard/tmp/work/x86_64-poky-linux-gnueabi/gcc-cross-arm/4.9.2-r0/gcc-4.9.2/build.x86_64-linux.arm-poky-linux-gnueabi/gcc'
| make: *** [all-gcc] Error 2
| ERROR: oe_runmake failed
| WARNING: /media/data/playground/wandboard/meta-wandboard/build-wandboard/tmp/work/x86_64-poky-linux-gnueabi/gcc-cross-arm/4.9.2-r0/temp/run.do_compile.1586:1 exit 1 from
|   exit 1
| ERROR: Function failed: do_compile (log file is located at /media/data/playground/wandboard/meta-wandboard/build-wandboard/tmp/work/x86_64-poky-linux-gnueabi/gcc-cross-arm/4.9.2-r0/temp/log.do_compile.1586)
ERROR: Task 996 (/media/data/playground/poky/meta/recipes-devtools/gcc/gcc-cross_4.9.bb, do_compile) failed with exit code '1'
NOTE: Tasks Summary: Attempted 1377 tasks of which 522 didn't need to be rerun and 1 failed.
Waiting for 0 running tasks to finish:

Summary: 1 task failed:
  /media/data/playground/poky/meta/recipes-devtools/gcc/gcc-cross_4.9.bb, do_compile
Summary: There were 5 WARNING messages shown.
Summary: There was 1 ERROR message shown, returning a non-zero exit code.

```

**Comment by gmalmeida** [comment]
Hi Scott, 

*it seems to be an issue with my VM*...

I am running the build now on a native linux server and I am able to generate the image...
